map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/yjo/espers2_ws/src/diffbot_description/config/map.yaml"

amcl:
  ros__parameters:
    use_map_topic: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    global_frame_id: "map"                   # ★ 누락 방지
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    laser_scan_topic: "/scan_filtered"
    transform_tolerance: 0.3                 # ★ TF 지연 보정 (기본 0.1 → 0.3)
    min_particles: 500
    max_particles: 2000
    update_min_d: 0.05                       # ★ 더 자주 업데이트 (기본 0.2m → 0.05m)
    update_min_a: 0.05                       # ★ 더 자주 회전 업데이트 (기본 0.2rad → 0.05rad)
    resample_interval: 1
    odom_alpha1: 0.1                         # ★ 오도메트리 모델 노이즈 보정
    odom_alpha2: 0.1
    odom_alpha3: 0.1
    odom_alpha4: 0.1

bt_navigator:
  ros__parameters:
    odom_topic: "/odom"

controller_server:
  ros__parameters:
    odom_topic: "/odom"
    use_sim_time: false
    controller_frequency: 20.0
    min_x_velocity: 0.0
    min_y_velocity: 0.0
    min_theta_velocity: 0.0
    
    progress_checker_plugin: "progress_checker"
    goal_dist_tol: 0.25
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3           # ★ 0.5 → 0.3 (짧은 이동에도 완료로 판단)

    goal_checker_plugins: ["goal_checker"]
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.2                  # ★ 목표 허용 오차를 조금 줄임
      yaw_goal_tolerance: 0.2

    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.2
      lookahead_dist: 0.3
      min_approach_linear_velocity: 0.05
      max_allowed_time_to_collision: 1.0

planner_server:
  ros__parameters:
    use_sim_time: false
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5

recoveries_server:
  ros__parameters:
    use_sim_time: false
    costmap_topic: "local_costmap/costmap_raw"
    footprint_topic: "local_costmap/published_footprint"

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: "odom"
      robot_base_frame: "base_link"
      update_frequency: 10.0                 # ★ 5Hz → 10Hz (갱신 빠르게)
      publish_frequency: 5.0                 # ★ 2Hz → 5Hz
      transform_tolerance: 0.3

      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      robot_radius: 0.22

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan_filtered
          data_type: "LaserScan"
          clearing: true
          marking: true
          obstacle_max_range: 3.0            # ★ 5.0 → 3.0 (더 가까운 범위만 신뢰)
          obstacle_min_range: 0.2            # ★ 0.4 → 0.2 (더 가까운 물체도 반영)

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.4                # ★ 조금 더 여유 있게 확장

      always_send_full_costmap: True

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: "map"
      robot_base_frame: "base_link"
      update_frequency: 3.0                  # ★ 1Hz → 3Hz (글로벌 갱신 가속)
      publish_frequency: 2.0                 # ★ 1Hz → 2Hz
      transform_tolerance: 0.5

      resolution: 0.05
      robot_radius: 0.22

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: /scan_filtered
          data_type: "LaserScan"
          clearing: true
          marking: true
          obstacle_max_range: 3.0
          obstacle_min_range: 0.2

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.4

      always_send_full_costmap: True




























# map_server:
#   ros__parameters:
#     use_sim_time: false
#     yaml_filename: "/home/yjo/espers2_ws/src/diffbot_description/config/map.yaml"

# amcl:
#   ros__parameters:
#     use_map_topic: true
#     odom_frame_id: "odom"
#     base_frame_id: "base_link"
#     robot_model_type: "nav2_amcl::DifferentialMotionModel"
#     laser_scan_topic: "/scan_filtered"        # ★ AMCL도 필터된 스캔 사용

# bt_navigator:
#   ros__parameters:
#     odom_topic: "/odom"

# controller_server:
#   ros__parameters:
#     odom_topic: "/odom"
#     use_sim_time: false
#     controller_frequency: 20.0
#     min_x_velocity: 0.0
#     min_y_velocity: 0.0
#     min_theta_velocity: 0.0
    
#     progress_checker_plugin: "progress_checker"
#     goal_dist_tol: 0.25
#     progress_checker:
#       plugin: "nav2_controller::SimpleProgressChecker"
#       required_movement_radius: 0.5
      
#     goal_checker_plugins: ["goal_checker"]
#     goal_checker:
#       plugin: "nav2_controller::SimpleGoalChecker"
#       xy_goal_tolerance: 0.25
#       yaw_goal_tolerance: 0.25

#     controller_plugins: ["FollowPath"]
#     FollowPath:
#       plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
#       desired_linear_vel: 0.2
#       lookahead_dist: 0.3
#       min_approach_linear_velocity: 0.05
#       max_allowed_time_to_collision: 1.0

# planner_server:
#   ros__parameters:
#     use_sim_time: false
#     planner_plugins: ["GridBased"]
#     GridBased:
#       plugin: "nav2_navfn_planner/NavfnPlanner"
#       tolerance: 0.5

# recoveries_server:
#   ros__parameters:
#     use_sim_time: false
#     costmap_topic: "local_costmap/costmap_raw"
#     footprint_topic: "local_costmap/published_footprint"

# local_costmap:
#   local_costmap:
#     ros__parameters:
#       use_sim_time: false
#       global_frame: "odom"
#       robot_base_frame: "base_link"
#       update_frequency: 5.0
#       publish_frequency: 2.0

#       rolling_window: true
#       width: 3
#       height: 3
#       resolution: 0.05
#       robot_radius: 0.22

#       plugins: ["obstacle_layer", "inflation_layer"]

#       obstacle_layer:
#         plugin: "nav2_costmap_2d::ObstacleLayer"
#         observation_sources: scan
#         scan:
#           topic: /scan_filtered           # ★ 필터 결과 사용
#           data_type: "LaserScan"
#           clearing: true
#           marking: true

#       inflation_layer:
#         plugin: "nav2_costmap_2d::InflationLayer"
#         inflation_radius: 0.35

#       always_send_full_costmap: True

# global_costmap:
#   global_costmap:
#     ros__parameters:
#       use_sim_time: false
#       global_frame: "map"
#       robot_base_frame: "base_link"
#       update_frequency: 1.0
#       publish_frequency: 1.0
#       resolution: 0.05
#       robot_radius: 0.22

#       plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

#       static_layer:
#         plugin: "nav2_costmap_2d::StaticLayer"
#         map_subscribe_transient_local: True

#       obstacle_layer:
#         plugin: "nav2_costmap_2d::ObstacleLayer"
#         observation_sources: scan
#         scan:
#           topic: /scan_filtered           # ★ 필터 결과 사용
#           data_type: "LaserScan"
#           clearing: true
#           marking: true

#       inflation_layer:
#         plugin: "nav2_costmap_2d::InflationLayer"
#         inflation_radius: 0.35

#       always_send_full_costmap: True


























# map_server:
#   ros__parameters:
#     use_sim_time: true
#     yaml_filename: "/home/yjo/espers2_ws/src/diffbot_description/config/map.yaml"

# amcl:
#   ros__parameters:
#     use_map_topic: true
#     odom_frame_id: "odom"
#     base_frame_id: "base_link"
#     robot_model_type: "nav2_amcl::DifferentialMotionModel"

# bt_navigator:
#   ros__parameters:
#     odom_topic: "/odom"

# controller_server:
#   ros__parameters:
#     odom_topic: "/odom"
#     use_sim_time: true
#     controller_frequency: 20.0
#     min_x_velocity: 0.0
#     min_y_velocity: 0.0
#     min_theta_velocity: 0.0
    
#     progress_checker_plugin: "progress_checker"
#     goal_dist_tol: 0.25
#     progress_checker:
#       plugin: "nav2_controller::SimpleProgressChecker"
#       required_movement_radius: 0.5
      
#     goal_checker_plugins: ["goal_checker"]
#     goal_checker:
#       plugin: "nav2_controller::SimpleGoalChecker"
#       xy_goal_tolerance: 0.25
#       yaw_goal_tolerance: 0.25

#     controller_plugins: ["FollowPath"]
#     FollowPath:
#       plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
#       desired_linear_vel: 0.2
#       lookahead_dist: 0.3
#       min_approach_linear_velocity: 0.05
#       max_allowed_time_to_collision: 1.0

# planner_server:
#   ros__parameters:
#     use_sim_time: true
#     planner_plugins: ["GridBased"]
#     GridBased:
#       plugin: "nav2_navfn_planner/NavfnPlanner" # ★★★ 최종 수정된 부분 ★★★
#       tolerance: 0.5

# recoveries_server:
#   ros__parameters:
#     use_sim_time: true
#     costmap_topic: "local_costmap/costmap_raw"
#     footprint_topic: "local_costmap/published_footprint"

# local_costmap:
#   local_costmap:
#     ros__parameters:
#       use_sim_time: true
#       global_frame: "odom"
#       robot_base_frame: "base_link"
#       update_frequency: 5.0
#       publish_frequency: 2.0


#       rolling_window: true
      
#       width: 3
#       height: 3
#       resolution: 0.05
#       robot_radius: 0.22
#       plugins: ["obstacle_layer", "inflation_layer"]
#       obstacle_layer:
#         plugin: "nav2_costmap_2d::ObstacleLayer"
#         observation_sources: scan
#         scan:
#           topic: /scan
#           data_type: "LaserScan"
#           clearing: true
#           marking: true
#       inflation_layer:
#         plugin: "nav2_costmap_2d::InflationLayer"
#         inflation_radius: 0.35
#       always_send_full_costmap: True

# global_costmap:
#   global_costmap:
#     ros__parameters:
#       use_sim_time: true
#       global_frame: "map"
#       robot_base_frame: "base_link"
#       update_frequency: 1.0
#       publish_frequency: 1.0
#       resolution: 0.05
#       robot_radius: 0.22
#       plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
#       static_layer:
#         plugin: "nav2_costmap_2d::StaticLayer"
#         map_subscribe_transient_local: True
#       obstacle_layer:
#         plugin: "nav2_costmap_2d::ObstacleLayer"
#         observation_sources: scan
#         scan:
#           topic: /scan
#           data_type: "LaserScan"
#           clearing: true
#           marking: true
#       inflation_layer:
#         plugin: "nav2_costmap_2d::InflationLayer"
#         inflation_radius: 0.35
#       always_send_full_costmap: True